[FLINK-33429] Tolerate missing metrics in the stabilization phase (#699)
The new code for the 1.7.0 release introduces metric collection during the
stabilization phase to allow sampling the observed true processing rate. Metrics
might not be fully initialized during that phase, as evident through the error
metrics. The following error is thrown:

```
java.lang.RuntimeException: Could not find required metric
NUM_RECORDS_OUT_PER_SEC for 667f5d5aa757fb217b92c06f0f5d2bf2
```

To prevent these errors shadowing actual errors, we should detect and ignore
this recoverable exception.